### ISSUE TITLE
Add support of asynchronous registration for module

### ISSUE THREAD

**Issue by thomasdom** [lambrohan/nestjs-meilisearch#1]
Currently, this module does not support async registration.

Async registration would be useful for getting configuration variables from `ConfigModule`, among many other use cases.

We should be able to register the module like this:

```ts
MeiliSearchModule.forRootAsync({
  imports: [ConfigModule],
  inject: [ConfigService],
  useFactory: (configService: ConfigService) => ({
    host: configService.get<string>('MEILISEARCH_HOST'),
    apiKey: configService.get<string>('MEILISEARCH_API_KEY'),
  }),
}),
```

**Comment by thomasdom** [comment]
@lambrohan Do you still maintain this repository?

**Comment by lambrohan** [comment]
@thomasdom Yes. I'll add the async registration support very soon.

**Comment by lambrohan** [comment]
@thomasdom Just did the update. It should support async module registration now.
