### ISSUE TITLE
Release `v2.0.7` ships without package (i.e., `/lib`)

### ISSUE THREAD

**Issue by kylejb** [lambrohan/nestjs-meilisearch#13]
## Reproduction Steps

1. Create a new project and install `nestjs-meilisearch` (v2.0.7)
2. Check `node_modules` directory

## Expected

Transpiled code should be packaged in `lib` directory.

## Actual

`lib` directory is missing in `v2.0.7`.

<img width="863" alt="Screenshot 2024-10-22 at 10 47 35" src="https://github.com/user-attachments/assets/5107169a-91fd-4df8-aeb6-ba6912ac7d37">

**Comment by lambrohan** [comment]
@kylejb good catch, it was stupid mistake on my part, sorry I just released the version with fix and wasn't aware of PR. 
https://www.npmjs.com/package/nestjs-meilisearch/v/2.1.8?activeTab=code should be fixed now

**Comment by kylejb** [comment]
All good, thanks for fixing it!

**Comment by kylejb** [comment]
@lambrohan, if you haven't already, I suggest pulling `2.0.7` from the registry so no one can mistakenly download that in the future.

**Comment by lambrohan** [comment]
Done, Thanks!
