### ISSUE TITLE
Add `meilisearch` as peer dependency

### ISSUE THREAD

**Issue by thomasdom** [lambrohan/nestjs-meilisearch#2]
Currently, the module uses `meilisearch` as a dependency, and at version `0.20.1`.

Each `meilisearch`'s version is tied to a specific server version.
Using a client version incompatible with server version will cause incompatibilities and may lead to unrecoverable application errors.

The module's user should be able to use any `meilisearch` version to match with its server implementation.

I also suggest to add `meilisearch` as dev dependency for module development.

**Comment by lambrohan** [comment]
@thomasdom That is a great suggestion. I'll update the repo soon.  Meanwhile please submit a PR if you like.

**Comment by thomasdom** [comment]
@lambrohan Ok, I'll try!

**Comment by thomasdom** [comment]
@lambrohan I've made a PR. Please feel free to review and help me to make better changes if needed, as I'm junior in NestJS library development. Thank you by advance!

**Comment by lambrohan** [comment]
@thomasdom  Awesome
