### ISSUE TITLE
Bump peer dependency for nest/common

### ISSUE THREAD

**Issue by chalettu** [lambrohan/nestjs-meilisearch#4]
Would it be possible to investigate adding peer dep support for Nest 9 for the nest/common package?

**Comment by lambrohan** [comment]
I'll publish a new release to support Nest 9 in a few upcoming days.

**Comment by lambrohan** [comment]
@chalettu new version has been released with latest `nestjs` and `meilisearch` deps.

https://github.com/lambrohan/nestjs-meilisearch/releases/tag/v2.1.2
