### ISSUE TITLE
@lambrohan you're sure the release is good ? I got some errors : `Cannot find module 'nestjs-meilisearch' or its corresponding type declarations.`

### ISSUE THREAD

**Issue by lefrancoisjc** [lambrohan/nestjs-meilisearch#9]
@lambrohan you're sure the release is good ? I got some errors : `Cannot find module 'nestjs-meilisearch' or its corresponding type declarations.`
Meanwhile I fixed it with an `npm run build` inside the node_module but now it's time to CI :P

_Originally posted by @jclappiway in https://github.com/lambrohan/nestjs-meilisearch/issues/8#issuecomment-1706792606_

**Comment by lefrancoisjc** [comment]
https://registry.npmjs.org/nestjs-meilisearch/-/nestjs-meilisearch-2.1.4.tgz ->  no lib folder

**Comment by lambrohan** [comment]
I have been using np to publish packages and it seems like there is problem with it now. Fixing
https://github.com/sindresorhus/np/issues/656

**Comment by lambrohan** [comment]
Released new version should work now
https://www.npmjs.com/package/nestjs-meilisearch/v/2.1.5 @jclappiway

**Comment by lefrancoisjc** [comment]
👍
